spring.application.name=product-service
server.port=8000

spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/db_product
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db_migration

#Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambiente containerizados
eureka.instance.prefer-ip-address=true
#Personalizar o id de cada instância
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço através do actuator, e não somente Heartbeat
# Opcional - Valor Default = TRUE
eureka.client.healthcheck.enabled=true

#Configuração mínima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
#ATENÇÃO: Cuidado a expor esses dados
#Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#Personalização de ifnormações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Servico responsavel pelo catalogo de produtos
info.app.autor=Bruno Galvagni
#Personalização de Metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=Brunog21/ExtraG1Microservices

#Definir a ulização das Probes Liveness e Readiness + exibição de de informações de componentes diversos
# Opcional: Padrão já é TRUE
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

# RESILIENCE PATTERNS - TIMEOUT
# Timeout para estabelecer conexão (1 segundo)
spring.cloud.openfeign.client.config.currency-service.connect-timeout=1000
# Timeout para processar e receber os dados (3 segundo)
spring.cloud.openfeign.client.config.currency-service.read-timeout=3000

# RESILIENCE PATTERNS - RETRY
# Quantidade máxima de tentativas (primeira  + 2 tentativas)
resilience4j.retry.instances.currency-service.max-attempts=3
# Tempo de espera inicial entre as tentativas
resilience4j.retry.instances.currency-service.wait-duration=500ms
# Ativa o recuo exponencial (Exponential Backoff)
resilience4j.retry.instances.currency-service.enable-exponential-backoff=true
# Multiplicador do tempo de espera (Tentativa 1: 500ms -> Tentativa 2: 500 x 2 = 1000ms)
resilience4j.retry.instances.currency-service.exponential-backoff-multiplier=2.0
# Ativa variação aleatório do tempo de espera (Jitter)
resilience4j.retry.instances.currency-service.enable-randomized-wait=true
# Fator do Jitter (Aplica uma flutação aleatória de até 50% para mais ou menos)
resilience4j.retry.instances.currency-service.randomized-wait-factor=0.5

# Regra de Exceção: IGNORAR/RETENTAR (um ou outro)
# IGNORAR (Evita desperdício de recursos em falhas do cliente)
# Ignora qualquer erro HTTP da família 4xx (400, 401, 403, 404, etc.)
resilience4j.retry.instances.currency-service.ignore-exceptions[0]=feign.FeignException\$FeignClientException

# RETENTAR (Foca apenas em falhas transitórias e instabilidades)
# Retenta em caso de timeout controlado pelo OpenFeign
resilience4j.retry.instances.currency-service.retry-exceptions[0]=feign.RetryableException
# Retenta em caso de queda drástica de socket/rede pura
resilience4j.retry.instances.currency-service.retry-exceptions[1]=java.net.SocketTimeoutException
# Retenta em caso de erros HTTP da família 5xx vindo do servidor (500, 502, 503, 504, etc.)
resilience4j.retry.instances.currency-service.retry-exceptions[2]=feign.FeignException\$FeignServerException

# RESILIENCE PATTERNS - CACHING
#Configura o tipo de cache. Para cache em memória o caffeine é considerado com melhor desempenho
spring.cache.type=caffeine
#Configurações do cache: 500 objetos no máximo e com um tempo de expiração de 15 segundos
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15s

# RESILIENCE PATTERNS - CIRCUIT BREAKER
#Habilita o Circuit Breaker do Resilience4j no OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.currency-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.currency-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.currency-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.currency-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.currency-service.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.currency-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.currency-service.automaticTransitionFromOpenToHalfOpenEnabled=true

#Habilita o actuator monitorar a saúde em conjunto com o circuit breaker
management.health.circuitbreakers.enabled=true


# Faz o OpenFeign usar o nome do microserviço como ID ... dessa forma sincroniza
# o retry com o circuit breaker
spring.cloud.openfeign.circuitbreaker.group.enabled=true
